// ui/src/public/components/public/Loading.vue
<template>
  <motion.div
    :initial="{ transformOrigin: 'center' }"
    :transition="{ repeat: Infinity, duration: 1, ease: 'linear' }"
    :animate="{ rotate: 360, display: 'flex', alignItems: 'center', justifyContent: 'center' }">
    <Loader />
  </motion.div>
</template>

<script setup lang="ts" name="Loading">
  import { motion } from "motion-v";
  import { Loader } from "lucide-vue-next";
</script>

<style scoped lang="scss"></style>

// ui/src/componets/public/Loading.tsx
import { FC, memo } from "react";
import { Loader } from "lucide-react";
import { motion, HTMLMotionProps } from "motion/react";

export type LoadingProps = HTMLMotionProps<"div">;

const Loading: FC<LoadingProps> = (props) => {
  return (
    <motion.div
      {...props}
      initial={{ transformOrigin: "center" }}
      animate={{
        rotate: 360,
        display: "flex",
        alignItems: "center",
        justifyContent: "center"
      }}
      transition={{ repeat: Infinity, duration: 1, ease: "linear" }}>
      <Loader />
    </motion.div>
  );
};
export default memo(Loading);
