// packages/ui/src/wins/tray/page/tray-page.vue
<template>
  <div class="w-screen h-screen overflow-hidden bg-white text-black rounded-md">
    <div class="px-1 py-2 w-40" ref="containerRef">
      <TrayPlayer
        v-if="Boolean(playerBus.data?.track?.detail)"
        :track="playerBus.data?.track?.detail!" />
      <TrayDivider v-if="Boolean(playerBus.data?.track?.detail)" />
      <TrayItem v-for="item in items" :icon="item.icon" :text="item.text" @click="item.click" />
    </div>
  </div>
</template>

<script setup lang="ts" name="Tray">
  import TrayItem from "@/wins/tray/page/tray-item.vue";
  import TrayPlayer from "@/wins/tray/page/tray-player.vue";
  import TrayDivider from "@/wins/tray/page/tray-divider.vue";
  import { RendererWindow } from "@/common/lib/window";
  import { RendererEventBus } from "@/common/lib/bus";
  import { useListenable } from "@/common/hooks/use-listenable-vue";
  import { computed, onMounted, onUnmounted, useTemplateRef, watch } from "vue";
  import {
    Copy,
    DiscAlbum,
    LogOut,
    MessageSquare,
    MicVocal,
    Pause,
    Play,
    SkipBack,
    SkipForward
  } from "lucide-vue-next";
  import { useThemeInjectFromBus } from "@/common/hooks/use-theme-inject-from-bus-vue";

  const containerRef = useTemplateRef<HTMLDivElement>("containerRef");
  const playerBus = useListenable(RendererEventBus.player);
  const currentWindow = useListenable(RendererWindow.current);
  // 主题
  useThemeInjectFromBus();
  // Actions
  function copy(text: Optional<string>) {
    if (!text) return;
    window.navigator.clipboard.writeText(text);
  }
  // Icons & Actions
  const items = computed(() => {
    const result = [
      {
        icon: SkipBack,
        text: "上一首",
        click: () => RendererEventBus.playerAction.send("previous")
      },
      {
        icon: SkipForward,
        text: "下一首",
        click: () => RendererEventBus.playerAction.send("next")
      },
      { icon: MicVocal, text: "歌手", click: () => {} },
      { icon: DiscAlbum, text: "专辑", click: () => {} },
      {
        icon: MessageSquare,
        text: "评论",
        click: async () => {
          const id = playerBus.value.data?.track?.id;
          if (!id) return;
          await RendererWindow.comment.openAwait();
          RendererEventBus.comment.send({
            id,
            type: "track"
          });
        }
      },
      {
        icon: Copy,
        text: "复制歌名",
        click: () => copy(playerBus.value.data?.track?.name)
      },
      {
        icon: Copy,
        text: "复制歌手名",
        click: () => copy(playerBus.value.data?.track?.detail?.ar.map((a) => a.name).join(" / "))
      },
      {
        icon: Copy,
        text: "复制专辑名",
        click: () => copy(playerBus.value.data?.track?.detail?.al.name)
      },
      {
        icon: LogOut,
        text: "退出",
        click: () => RendererEventBus.playerAction.send("exit")
      }
    ];
    if (playerBus.value.data?.status === "playing") {
      result.unshift({
        icon: Pause,
        text: "暂停",
        click: () => RendererEventBus.playerAction.send("pause")
      });
    } else {
      result.unshift({
        icon: Play,
        text: "播放",
        click: () => RendererEventBus.playerAction.send("play")
      });
    }
    return result;
  });
  // 修改窗口标题
  watch(playerBus, (playerBus) => {
    const name = playerBus.data?.track?.name;
    const artist = playerBus.data?.track?.detail.ar.map((a) => a.name).join(" / ");
    if (name && artist) {
      document.title = `${name} - ${artist}`;
    }
  });
  // 动态调整窗口大小
  let observer: ResizeObserver;
  onMounted(() => {
    observer = new ResizeObserver(() => {
      const deltaX = window.innerWidth - (containerRef.value?.offsetWidth || window.innerWidth);
      const deltaY = window.innerHeight - (containerRef.value?.offsetHeight || window.innerHeight);
      currentWindow.value.resize({
        width: containerRef.value?.offsetWidth || window.innerWidth,
        height: containerRef.value?.offsetHeight || window.innerHeight
      });
      currentWindow.value.move({
        x: window.screenX + deltaX,
        y: window.screenY + deltaY
      });
    });
    containerRef.value && observer.observe(containerRef.value);
  });
  onUnmounted(() => {
    observer.disconnect();
  });
</script>

<style scoped lang="scss"></style>

// packages/ui/src/wins/tray/page/tray-page.tsx
import { type FC, memo, useCallback, useEffect, useLayoutEffect, useMemo, useRef } from "react";
import {
  Copy,
  DiscAlbum,
  ExternalLink,
  LogOut,
  MessageSquare,
  MicVocal,
  Pause,
  Play,
  SkipBack,
  SkipForward,
  type LucideIcon
} from "lucide-react";
import AppToast from "@/common/components/toast";
import { useListenable } from "@/common/hooks/use-listenable";
import { useThemeInjectFromBus } from "@/common/hooks/use-theme-inject-from-bus";
import { RendererEventBus } from "@/common/lib/bus";
import { RendererWindow } from "@/common/lib/window";

import TrayDivider from "./tray-divider";
import TrayItem from "./tray-item";
import TrayPlayer from "./tray-player";

type TrayAction = {
  icon: LucideIcon;
  text: string;
  active?: boolean;
  danger?: boolean;
  disabled?: boolean;
  onClick: NormalFunc;
};

const TrayPage: FC = () => {
  const containerRef = useRef<HTMLDivElement>(null);
  const playerBus = useListenable(RendererEventBus.player);
  const progressBus = useListenable(RendererEventBus.progress);
  const mainWindow = useListenable(RendererWindow.main);
  const currentWindow = useListenable(RendererWindow.current);
  const trackRecord = playerBus.data?.track;
  const track = trackRecord?.detail;
  const isPlaying = playerBus.data?.status === "playing";
  const artistName = track?.ar.map((item) => item.name).join(" / ");
  const firstArtistID = track?.ar.find((item) => item.id > 0)?.id;
  const albumID = track?.al.id && track.al.id > 0 ? track.al.id : undefined;

  useThemeInjectFromBus();

  useLayoutEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    let frame = 0;
    const updateWindowBounds = () => {
      window.cancelAnimationFrame(frame);
      frame = window.requestAnimationFrame(() => {
        const width = Math.ceil(container.offsetWidth || window.innerWidth);
        const height = Math.ceil(container.offsetHeight || window.innerHeight);
        const deltaX = window.innerWidth - width;
        const deltaY = window.innerHeight - height;

        currentWindow.resize({ width, height });
        currentWindow.move({
          x: window.screenX + deltaX,
          y: window.screenY + deltaY
        });
      });
    };

    const observer = new ResizeObserver(updateWindowBounds);
    observer.observe(container);
    updateWindowBounds();

    return () => {
      window.cancelAnimationFrame(frame);
      observer.disconnect();
    };
  }, [currentWindow]);

  useEffect(() => {
    document.title = track?.name && artistName ? `${track.name} - ${artistName}` : "AiraMusic";
  }, [artistName, track?.name]);

  const hideTray = useCallback(() => currentWindow.hide(), [currentWindow]);

  const copy = useCallback(async (text: Optional<string>, label: string) => {
    if (!text) return;
    try {
      await window.navigator.clipboard.writeText(text);
      AppToast.show({ type: "success", text: `${label}已复制` });
    } catch {
      AppToast.show({ type: "error", text: `${label}复制失败` });
    }
  }, []);

  const openDisplay = useCallback(
    async (data: { type: "album" | "artist"; id: number }) => {
      await RendererWindow.display.openAwait();
      RendererEventBus.display.send(data);
      hideTray();
    },
    [hideTray]
  );

  const openComment = useCallback(async () => {
    const id = trackRecord?.id;
    if (!id) return;
    await RendererWindow.comment.openAwait();
    RendererEventBus.comment.send({
      id,
      type: "track"
    });
    hideTray();
  }, [hideTray, trackRecord?.id]);

  const showMainWindow = useCallback(() => {
    mainWindow.show();
    mainWindow.focus();
    hideTray();
  }, [hideTray, mainWindow]);

  const playbackActions = useMemo<TrayAction[]>(
    () => [
      {
        icon: isPlaying ? Pause : Play,
        text: isPlaying ? "暂停" : "播放",
        active: true,
        onClick: () => RendererEventBus.playerAction.send(isPlaying ? "pause" : "play")
      },
      {
        icon: SkipBack,
        text: "上一首",
        onClick: () => RendererEventBus.playerAction.send("previous")
      },
      {
        icon: SkipForward,
        text: "下一首",
        onClick: () => RendererEventBus.playerAction.send("next")
      }
    ],
    [isPlaying]
  );

  const detailActions = useMemo<TrayAction[]>(
    () => [
      {
        icon: MicVocal,
        text: "查看歌手",
        disabled: !firstArtistID,
        onClick: () => firstArtistID && void openDisplay({ type: "artist", id: firstArtistID })
      },
      {
        icon: DiscAlbum,
        text: "查看专辑",
        disabled: !albumID,
        onClick: () => albumID && void openDisplay({ type: "album", id: albumID })
      },
      {
        icon: MessageSquare,
        text: "查看评论",
        disabled: !trackRecord?.id,
        onClick: () => void openComment()
      }
    ],
    [albumID, firstArtistID, openComment, openDisplay, trackRecord?.id]
  );

  const copyActions = useMemo<TrayAction[]>(
    () => [
      {
        icon: Copy,
        text: "复制歌名",
        disabled: !track?.name,
        onClick: () => void copy(track?.name, "歌名")
      },
      {
        icon: Copy,
        text: "复制歌手名",
        disabled: !artistName,
        onClick: () => void copy(artistName, "歌手名")
      },
      {
        icon: Copy,
        text: "复制专辑名",
        disabled: !track?.al.name,
        onClick: () => void copy(track?.al.name, "专辑名")
      }
    ],
    [artistName, copy, track?.al.name, track?.name]
  );

  const systemActions = useMemo<TrayAction[]>(
    () => [
      {
        icon: ExternalLink,
        text: "打开主窗口",
        onClick: showMainWindow
      },
      {
        icon: LogOut,
        text: "退出",
        danger: true,
        onClick: () => RendererEventBus.playerAction.send("exit")
      }
    ],
    [showMainWindow]
  );

  return (
    <div className="h-screen w-screen overflow-hidden bg-transparent text-black">
      <div
        ref={containerRef}
        className="
          w-[13.5rem] rounded-xl border border-black/8 bg-white/96 p-2
          shadow-[0_18px_50px_rgba(0,0,0,0.22)] backdrop-blur-xl
        ">
        <TrayPlayer
          track={track}
          status={playerBus.data?.status}
          currentTime={progressBus.data?.currentTime}
          duration={progressBus.data?.duration}
        />
        <TrayDivider />
        <TrayGroup actions={playbackActions} />
        <TrayDivider />
        <TrayGroup actions={detailActions} />
        <TrayDivider />
        <TrayGroup actions={copyActions} />
        <TrayDivider />
        <TrayGroup actions={systemActions} />
      </div>
      <AppToast.Provider className="top-2 z-50" />
    </div>
  );
};

const TrayGroup: FC<{ actions: TrayAction[] }> = memo(({ actions }) => {
  return (
    <div className="grid gap-0.5">
      {actions.map((item) => (
        <TrayItem key={item.text} {...item} />
      ))}
    </div>
  );
});

export default memo(TrayPage);
