// packages/ui/src/common/components/fallback/AppLoading.vue
<template>
  <div
    v-if="props.loading"
    :style="{ color: props.color }"
    class="px-2 py-1 w-full h-full flex flex-col gap-2 justify-center items-center text-white">
    <Loading class="size-8" />
    <span class="font-semibold">{{ props.tips }}</span>
  </div>
  <slot v-else name="default" />
</template>

<script setup lang="ts" name="AppLoading">
  import { ReactNode } from "react";
  import Loading from "@mahiru/ui/common/components/public/Loading.vue";

  const props = withDefaults(
    defineProps<{
      loading: boolean;
      color?: string;
      children?: ReactNode;
      tips?: string;
    }>(),
    {
      tips: "数据努力加载中"
    }
  );
</script>

<style scoped lang="scss"></style>

// packages/ui/src/public/components/fallback/AppLoading.tsx
import Loading from "@mahiru/ui/public/components/public/Loading";
import { FC, memo, ReactNode } from "react";
import { useThemeColor } from "@mahiru/ui/public/hooks/useThemeColor";
import { cx } from "@emotion/css";

interface ListLoadingProps {
  loading: boolean;
  color?: string;
  children?: ReactNode;
  className?: string;
  tips?: string;
}

const AppLoading: FC<ListLoadingProps> = ({
  loading,
  children,
  className,
  tips = "数据努力加载中",
  color
}) => {
  const { mainColor } = useThemeColor();
  if (!loading) return <>{children}</>;
  return (
    <div
      style={{ color: color || mainColor.hex() }}
      className={cx(
        "px-2 py-1 w-full h-full flex flex-col gap-2 justify-center items-center",
        className
      )}>
      <Loading className="size-8" />
      <span className="font-semibold">{tips}</span>
    </div>
  );
};

export default memo(AppLoading);
