// packages/ui/src/wins/tray/page/tray-item.tsx
import { cx } from "@emotion/css";
import { type FC, memo } from "react";
import type { LucideIcon } from "lucide-react";

interface TrayItemProps {
  icon: LucideIcon;
  text: string;
  active?: boolean;
  danger?: boolean;
  disabled?: boolean;
  onClick: NormalFunc;
}

const TrayItem: FC<TrayItemProps> = ({ icon: Icon, text, active, danger, disabled, onClick }) => {
  return (
    <button
      type="button"
      title={text}
      disabled={disabled}
      onClick={() => onClick()}
      className={cx(
        `
          group flex h-8 w-full items-center gap-2 rounded-md px-2 text-left
          text-[12px] font-semibold outline-none transition-all duration-300 ease-in-out
          focus-visible:ring-2 focus-visible:ring-(--theme-color-main)/40
        `,
        active
          ? "bg-(--theme-color-main) text-(--text-color-on-main)"
          : "hover:bg-black/20 active:scale-[0.98]",
        danger && "text-red-600 hover:bg-red-500/10 hover:text-red-700",
        disabled && "pointer-events-none opacity-35"
      )}>
      <Icon className="size-4 shrink-0" />
      <span className="min-w-0 flex-1 truncate">{text}</span>
    </button>
  );
};

export default memo(TrayItem);

// ui/src/tray/page/TrayItem.vue
<template>
  <div
    class="flex items-center gap-1.5 px-2 py-1 rounded-md hover:bg-(--theme-color-main)/60 hover:text-(--text-color-on-main) cursor-pointer">
    <Icon size="14" />
    <span class="text-[12px]">{{ props.text }}</span>
  </div>
</template>

<script setup lang="ts" name="TrayItem">
  import { Component, computed } from "vue";

  const props = defineProps<{ icon: Component; text: string }>();
  const Icon = computed(() => props.icon);
</script>

<style scoped lang="scss"></style>
