// packages/ui/src/wins/mini/page/mini-player-page.tsx
import { clamp } from "lodash-es";
import { Pause, Play, SkipBack, SkipForward, X, Music2, type LucideIcon } from "lucide-react";
import { type FC, memo, useCallback, useMemo } from "react";
import Drag from "@/common/components/drag/drag";
import NoDrag from "@/common/components/drag/no-drag";
import NeteaseImage from "@/common/components/image/netease-image";
import { NeteaseImageSize } from "@/common/enum";
import { useListenable } from "@/common/hooks/use-listenable";
import { RendererEventBus } from "@/common/lib/bus";
import { RendererWindow } from "@/common/lib/window";
import { NeteaseNetworkImage } from "@/common/netease/models";

interface ControlButtonProps {
  icon: LucideIcon;
  label: string;
  active?: boolean;
  onClick: NormalFunc;
}

const ControlButton: FC<ControlButtonProps> = ({ icon: Icon, label, active, onClick }) => {
  return (
    <button
      type="button"
      title={label}
      aria-label={label}
      onClick={onClick}
      className="
        flex size-5 items-center justify-center rounded-full text-black/75 outline-none
        transition-all duration-200 ease-in-out hover:bg-black/8 hover:text-black
        active:scale-90 focus-visible:ring-2 focus-visible:ring-(--theme-color-main)/35
      ">
      <Icon className="size-3.5" fill={active ? "currentColor" : "none"} />
    </button>
  );
};

const MemoControlButton = memo(ControlButton);

const MiniPlayerPage: FC = () => {
  const mainWindow = useListenable(RendererWindow.main);
  const currentWindow = useListenable(RendererWindow.current);
  const playerBus = useListenable(RendererEventBus.player);
  const progressBus = useListenable(RendererEventBus.progress);
  const track = playerBus.data?.track?.detail;
  const isPlaying = playerBus.data?.status === "playing";
  const artist = track?.ar.map((item) => item.name).join(" / ");
  const percent = useMemo(() => {
    const duration = progressBus.data?.duration || (track?.dt ?? 0) / 1000 || 1;
    return clamp(((progressBus.data?.currentTime || 0) / duration) * 100, 0, 100);
  }, [progressBus.data?.currentTime, progressBus.data?.duration, track?.dt]);
  const image = useMemo(
    () =>
      NeteaseNetworkImage.fromTrackCover(track)
        ?.setSize(NeteaseImageSize.sm)
        .setAlt(track?.name || track?.al.name),
    [track]
  );

  const close = useCallback(() => {
    currentWindow.hide();
    mainWindow.show();
    mainWindow.focus();
  }, [currentWindow, mainWindow]);

  const togglePlay = useCallback(() => {
    RendererEventBus.playerAction.send(isPlaying ? "pause" : "play");
  }, [isPlaying]);

  return (
    <Drag
      className="
        grid h-screen w-screen grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2
        overflow-hidden rounded-lg border border-black/8 bg-white/96 px-2 py-1 text-black
        shadow-[0_10px_30px_rgba(0,0,0,0.16)] backdrop-blur-xl
      ">
      <div className="relative size-11 overflow-hidden rounded-md border border-black/8 bg-black/5">
        {image ? (
          <NeteaseImage
            cache
            cacheLazy={false}
            image={image}
            shadow="none"
            className="size-full"
            imageClassName="object-cover"
          />
        ) : (
          <div className="flex size-full items-center justify-center text-black/35">
            <Music2 className="size-5" />
          </div>
        )}
        <span className="absolute inset-x-0 bottom-0 h-0.5 bg-black/12">
          <span
            className="block h-full bg-(--theme-color-main) transition-[width] duration-300 ease-in-out"
            style={{ width: `${percent}%` }}
          />
        </span>
      </div>
      <div className="grid min-w-0 grid-rows-[1fr_auto] gap-0.5">
        <div className="min-w-0 self-end">
          <p className="truncate text-[12px] font-black leading-4">{track?.name || "暂无播放"}</p>
          <p className="truncate text-[9px] font-semibold leading-3 text-black/45">
            {artist || track?.al.name || "AiraMusic"}
          </p>
        </div>
        <NoDrag className="flex items-center justify-start gap-1">
          <MemoControlButton
            icon={SkipBack}
            label="上一首"
            onClick={() => RendererEventBus.playerAction.send("previous")}
          />
          <MemoControlButton
            icon={isPlaying ? Pause : Play}
            label={isPlaying ? "暂停" : "播放"}
            active={isPlaying}
            onClick={togglePlay}
          />
          <MemoControlButton
            icon={SkipForward}
            label="下一首"
            onClick={() => RendererEventBus.playerAction.send("next")}
          />
        </NoDrag>
      </div>
      <NoDrag className="self-start">
        <button
          type="button"
          title="隐藏迷你播放器"
          aria-label="隐藏迷你播放器"
          onClick={close}
          className="
            flex size-5 items-center justify-center rounded-full text-black/45 outline-none
            transition-all duration-200 ease-in-out hover:bg-black/8 hover:text-black
            active:scale-90 focus-visible:ring-2 focus-visible:ring-(--theme-color-main)/35
          ">
          <X className="size-3.5" />
        </button>
      </NoDrag>
    </Drag>
  );
};

export default memo(MiniPlayerPage);

// packages/ui/src/windows/mini/page/MiniPlayerPage.vue
<template>
  <Drag
    class="w-screen h-screen overflow-hidden relative bg-white rounded-md text-black grid grid-rows-1 grid-cols-[auto_1fr] px-2 py-1 items-center select-none">
    <div class="h-12 w-12 rounded-md overflow-hidden border border-gray-300/50">
      <NeteaseImage
        :cache="true"
        :image="image"
        style="width: 100%; height: 100%"
        shadow-color="dark" />
    </div>
    <div class="h-full w-full flex flex-col justify-center px-2 gap-1.5 overflow-hidden">
      <div class="flex items-center justify-center gap-1">
        <span class="text-[12px] font-bold truncate">{{ track?.name }}</span>
        <span class="text-[12px]"> - </span>
        <span class="text-[10px] font-medium truncate opacity-50">
          {{ track?.ar?.map((a) => a.name).join("/") }}
        </span>
      </div>
      <div class="grid grid-rows-1 grid-cols-[1fr_auto] items-center justify-center gap-1">
        <div class="h-1.25 bg-gray-500 rounded-full overflow-hidden">
          <span
            class="h-full block bg-white/80 ease-in-out duration-300 transition-all"
            :style="{ width: `${percent}%` }" />
        </div>
      </div>
      <NoDrag class="flex items-center gap-2 justify-center">
        <SkipBack
          class="size-3 hover:scale-90 hover:opacity-50 active:scale-80 cursor-pointer ease-in-out transition-all duration-300"
          @click="ElectronServices.Bus.playerAction.send('previous')"
          fill="#171b20" />
        <Pause
          v-if="playerBus.data?.status === 'playing'"
          class="size-3 hover:scale-90 hover:opacity-50 active:scale-80 cursor-pointer ease-in-out transition-all duration-300"
          @click="ElectronServices.Bus.playerAction.send('pause')"
          fill="#171b20" />
        <Play
          v-else
          class="size-3 hover:scale-90 hover:opacity-50 active:scale-80 cursor-pointer ease-in-out transition-all duration-300"
          @click="ElectronServices.Bus.playerAction.send('play')"
          fill="#171b20" />
        <SkipForward
          class="size-3 hover:scale-90 hover:opacity-50 active:scale-80 cursor-pointer ease-in-out transition-all duration-300"
          @click="ElectronServices.Bus.playerAction.send('next')"
          fill="#171b20" />
      </NoDrag>
    </div>
    <NoDrag class="absolute right-1 top-1">
      <X class="size-4 hover:opacity-50 cursor-pointer active:text-white/80" @click="close" />
    </NoDrag>
  </Drag>
</template>
<script setup lang="ts">
  import Drag from "@mahiru/ui/public/components/drag/Drag.vue";
  import NoDrag from "@mahiru/ui/public/components/drag/NoDrag.vue";
  import NeteaseImage from "@mahiru/ui/public/components/image/NeteaseImage.vue";
  import ElectronServices from "@mahiru/ui/public/source/electron/services";
  import { useListenable } from "@mahiru/ui/public/hooks/useListenableVue";
  import { Pause, Play, SkipBack, SkipForward, X } from "lucide-vue-next";
  import { computed } from "vue";
  import { clamp } from "lodash-es";
  import { NeteaseNetworkImage } from "@mahiru/ui/public/source/netease/models";
  import { NeteaseImageSize } from "@mahiru/ui/public/enum";

  const mainWindow = useListenable(ElectronServices.Window.main);
  const currentWindow = useListenable(ElectronServices.Window.current);
  const playerBus = useListenable(ElectronServices.Bus.player);
  const progressBus = useListenable(ElectronServices.Bus.progress);
  const track = computed(() => playerBus.value.data?.track?.detail);
  const percent = computed(() => {
    const currentTime = progressBus.value.data?.currentTime || 0;
    const duration = progressBus.value.data?.duration || 1;
    return clamp((currentTime / duration) * 100, 0, 100);
  });
  const image = computed(() => {
    return NeteaseNetworkImage.fromTrackCover(track.value)?.setSize(NeteaseImageSize.sm);
  });

  function close() {
    currentWindow.value.hide();
    mainWindow.value.show();
  }
</script>
<style scoped lang="scss"></style>
