// packages/ui/src/common/components/top/control.vue
<template>
  <NoDrag class="flex flex-row gap-4 select-none relative z-50">
    <AppWindowIcon
      v-if="RendererRuntime.isDev"
      :color="props.color"
      class="size-5 control-button"
      @click="currentWindow.devTools()" />
    <Minus
      v-if="props.mini"
      :color="props.color"
      class="size-5 control-button"
      @click="currentWindow.minimize()" />
    <Square
      v-if="props.maximizable"
      v-show="currentWindow.isMax"
      :color="props.color"
      class="size-5 control-button"
      @click="currentWindow.unmaximize()" />
    <SquareMinus
      v-if="props.maximizable"
      v-show="!currentWindow.isMax"
      :color="props.color"
      class="size-5 control-button"
      @click="currentWindow.maximize()" />
    <X :color="props.color" class="size-5 control-button" @click="currentWindow.close()" />
  </NoDrag>
</template>

<script setup lang="ts" name="TopControlPure">
  import NoDrag from "@/common/components/drag/no-drag.vue";
  import { AppWindow as AppWindowIcon, Minus, Square, SquareMinus, X } from "lucide-vue-next";
  import { useListenable } from "@/common/hooks/use-listenable-vue";
  import { ElectronServicesWindow } from "@/common/source/electron/services";
  import { RendererRuntime } from "@/common/lib/runtime";

  const currentWindow = useListenable(ElectronServicesWindow.current);

  const props = withDefaults(
    defineProps<{
      maximizable?: boolean;
      mini?: boolean;
      color?: string;
    }>(),
    {
      mini: true
    }
  );
</script>

<style scoped lang="scss">
  .control-button {
    cursor: pointer;
    scale: 80%;
    transition: all ease-in-out 0.3s;

    &:hover {
      opacity: 0.5;
    }
  }
</style>

// packages/ui/src/common/components/top/control.tsx
import { cx } from "@emotion/css";
import { type FC, memo } from "react";
import { AppWindow as AppWindowIcon, Minus, Square, SquareMinus, X } from "lucide-react";
import { useListenable } from "@/common/hooks/use-listenable";
import { ElectronServicesWindow } from "@/common/source/electron/services";
import { RendererRuntime } from "@/common/lib/runtime";

import NoDrag from "@/common/components/drag/no-drag";

interface TopControlProps {
  maximizable?: boolean;
  mini?: boolean;
  color?: string;
  className?: string;
}

const TopControlPure: FC<TopControlProps> = ({ maximizable, mini = true, color, className }) => {
  const currentWindow = useListenable(ElectronServicesWindow.current);

  return (
    <NoDrag className={cx(`flex flex-row gap-4 select-none relative`, className)}>
      {RendererRuntime.isDev && (
        <AppWindowIcon
          color={color}
          className="size-5 cursor-pointer hover:opacity-50 ease-in-out transition-all duration-300"
          onClick={() => currentWindow.devTools()}
        />
      )}
      {mini && (
        <Minus
          color={color}
          className="size-5 cursor-pointer hover:opacity-50 ease-in-out transition-all duration-300"
          onClick={() => currentWindow.minimize()}
        />
      )}
      {maximizable &&
        (currentWindow.isMax ? (
          <SquareMinus
            color={color}
            className="size-5 cursor-pointer scale-80 hover:opacity-50 ease-in-out transition-all duration-300"
            onClick={() => currentWindow.maximize()}
          />
        ) : (
          <Square
            color={color}
            className="size-5 cursor-pointer scale-80 hover:opacity-50 ease-in-out transition-all duration-300"
            onClick={() => currentWindow.maximize()}
          />
        ))}
      <X
        color={color}
        className="size-5 cursor-pointer hover:opacity-50 ease-in-out transition-all duration-300"
        onClick={() => currentWindow.close()}
      />
    </NoDrag>
  );
};

export default memo(TopControlPure);
