// packages/ui/src/common/components/public/TopControlPure.tsx
import { cx } from "@emotion/css";
import { type FC, memo } from "react";
import { AppWindow as AppWindowIcon, Minus, Square, SquareMinus, X } from "lucide-react";
import { isDev } from "@mahiru/ui/common/constants/dev";
import { useListenable } from "../../hooks/useListenable";
import { ElectronServicesWindow } from "../../source/electron/services";

import NoDrag from "../../components/drag/NoDrag";

interface TopControlPurProps {
  maximizable?: boolean;
  mini?: boolean;
  color?: string;
  className?: string;
}

const TopControlPure: FC<TopControlPurProps> = ({ maximizable, mini = true, color, className }) => {
  const currentWindow = useListenable(ElectronServicesWindow.current);

  return (
    <NoDrag className={cx(`flex flex-row gap-4 select-none relative z-50`, className)}>
      {isDev && (
        <AppWindowIcon
          color={color}
          className="size-5 cursor-pointer hover:opacity-50 ease-in-out transition-all duration-300"
          onClick={() => currentWindow.devTools()}
        />
      )}
      {mini && (
        <Minus
          color={color}
          className="size-5 cursor-pointer hover:opacity-50 ease-in-out transition-all duration-300"
          onClick={() => currentWindow.minimize()}
        />
      )}
      {maximizable &&
        (currentWindow.isMax ? (
          <SquareMinus
            color={color}
            className="size-5 cursor-pointer scale-80 hover:opacity-50 ease-in-out transition-all duration-300"
            onClick={() => currentWindow.maximize()}
          />
        ) : (
          <Square
            color={color}
            className="size-5 cursor-pointer scale-80 hover:opacity-50 ease-in-out transition-all duration-300"
            onClick={() => currentWindow.maximize()}
          />
        ))}
      <X
        color={color}
        className="size-5 cursor-pointer hover:opacity-50 ease-in-out transition-all duration-300"
        onClick={() => currentWindow.close()}
      />
    </NoDrag>
  );
};

export default memo(TopControlPure);

// packages/ui/src/common/components/public/TopControlPure.vue
<template>
  <NoDrag class="flex flex-row gap-4 select-none relative z-50">
    <AppWindowIcon
      v-if="isDev"
      :color="props.color"
      class="size-5 control-button"
      @click="currentWindow.devTools()" />
    <Minus
      v-if="props.mini"
      :color="props.color"
      class="size-5 control-button"
      @click="currentWindow.minimize()" />
    <Square
      v-if="props.maximizable"
      v-show="currentWindow.isMax"
      :color="props.color"
      class="size-5 control-button"
      @click="currentWindow.unmaximize()" />
    <SquareMinus
      v-if="props.maximizable"
      v-show="!currentWindow.isMax"
      :color="props.color"
      class="size-5 control-button"
      @click="currentWindow.maximize()" />
    <X :color="props.color" class="size-5 control-button" @click="currentWindow.close()" />
  </NoDrag>
</template>

<script setup lang="ts" name="TopControlPure">
  import NoDrag from "@mahiru/ui/common/components/drag/NoDrag.vue";
  import { AppWindow as AppWindowIcon, Minus, Square, SquareMinus, X } from "lucide-vue-next";
  import { isDev } from "@mahiru/ui/common/constants/dev";
  import { useListenable } from "@mahiru/ui/common/hooks/useListenableVue";
  import { ElectronServicesWindow } from "@mahiru/ui/common/source/electron/services";

  const currentWindow = useListenable(ElectronServicesWindow.current);

  const props = withDefaults(
    defineProps<{
      maximizable?: boolean;
      mini?: boolean;
      color?: string;
    }>(),
    {
      mini: true
    }
  );
</script>

<style scoped lang="scss">
  .control-button {
    cursor: pointer;
    scale: 80%;
    transition: all ease-in-out 0.3s;

    &:hover {
      opacity: 0.5;
    }
  }
</style>
