// packages/ui/src/common/components/image/ImageViewer.vue
<template>
  <div class="w-full h-full relative" @mousemove.passive="toggleToolBar(true)">
    <slot class="absolute" name="default" />
    <div class="viewer-title" :class="toolBarVisible && 'active'">
      <span class="max-w-2/3 truncate text-center">
        {{ current.alt || current.url }}
      </span>
      <span v-if="props.images.length && props.images.length > 1">
        {{ ` (${index + 1}/${props.images.length}) ` }}
      </span>
    </div>
    <div class="viewer-button" :class="toolBarVisible && 'active'">
      <ArrowLeftToLine
        v-if="props.images.length > 1"
        class="cursor-pointer hover:opacity-50 active:scale-90 duration-300 transition-all ease-in-out size-5"
        color="#ffffff"
        @click.passive="lastImage" />
      <Download
        class="cursor-pointer hover:opacity-50 active:scale-90 duration-300 transition-all ease-in-out size-5"
        color="#ffffff"
        @click.passive="saveImage" />
      <ArrowRightToLine
        v-if="props.images.length > 1"
        class="cursor-pointer hover:opacity-50 active:scale-90 duration-300 transition-all ease-in-out size-5"
        color="#ffffff"
        @click.passive="nextImage" />
    </div>
    <AppLoading class="viewer" :loading="status === 'loading'" />
    <div
      ref="viewerRef"
      class="viewer"
      @wheel.prevent="onWheel"
      @pointerdown.passive="onPointerDown"
      @pointermove.passive="onPointerMove"
      @pointerup.passive="onPointerUp"
      @pointerleave.passive="onPointerUp">
      <img
        :src="current?.url"
        :alt="current?.alt"
        :style="imgStyle"
        :class="status === 'loaded' ? 'opacity-100' : 'opacity-0'"
        ref="imageRef"
        draggable="false"
        @load="status = 'loaded'"
        @error="status = 'error'" />
    </div>
  </div>
</template>

<script setup lang="ts" name="ImageViewer">
  import { computed, CSSProperties, onMounted, ref, useTemplateRef, watch } from "vue";
  import { clamp } from "lodash-es";
  import { ArrowLeftToLine, ArrowRightToLine, Download } from "lucide-vue-next";
  import { Log } from "@mahiru/ui/common/constants/dev";
  import { ElectronServicesIPC } from "@mahiru/ui/common/source/electron/services";
  import AppLoading from "@mahiru/ui/common/components/fallback/AppLoading.vue";

  type ImageEntry = { url?: string; alt?: string };

  const viewerRef = useTemplateRef<HTMLDivElement>("viewerRef");
  const imageRef = useTemplateRef<HTMLImageElement>("imageRef");
  const status = ref<"loading" | "error" | "loaded">("loading");
  const props = defineProps<{ images: ImageEntry[] }>();
  const index = ref(0);
  const current = computed<ImageEntry>(() => {
    return props.images[index.value] || {};
  });
  const scale = ref(1);
  const translate = ref({ x: 0, y: 0 });
  const dragging = ref(false);
  const toolBarVisible = ref(false);
  const moved = ref(false);
  const imgStyle = computed<CSSProperties>(() => {
    return {
      transform: `translate(${translate.value.x}px, ${translate.value.y}px) scale(${scale.value})`,
      transition: dragging.value ? `none` : `transform 0.2s ease`,
      cursor: moved.value ? `move` : `default`
    };
  });
  const emit = defineEmits<{
    (e: "toolBarChange", visible: boolean): void;
  }>();

  watch(current, () => {
    document.title = current.value.alt || current.value.url || "Image Viewer";
  });

  watch(
    () => [props.images, props.images.length],
    () => {
      if (index.value !== props.images.length - 1) {
        status.value = "loading";
        index.value = Math.max(0, props.images.length - 1);
      }
    }
  );

  onMounted(() => {
    emit("toolBarChange", toolBarVisible.value);
  });

  async function saveImage() {
    if (status.value === "loaded" && current.value.url) {
      try {
        let type = "";
        const buffer = await fetch(current.value.url).then((res) => {
          if (!res.ok) Log.throw({ message: "网络错误" });
          const contentType = res.headers.get("content-type");
          if (contentType) type = contentType.split("/")[1]?.split(";")[0] || "jpg";
          return res.arrayBuffer();
        });
        const splitSrc = current.value.url.split("/");
        const name =
          (current.value.alt ? `${current.value.alt}.${type}` : "") ||
          splitSrc[splitSrc.length - 1] ||
          current.value.url ||
          `unknown.${type}`;
        const result = (await ElectronServicesIPC.Event.invoke.saveFile(<
          { buffer: ArrayBuffer; name: string }
        >{
          buffer,
          name
        })) as { error?: string; ok: boolean };
        if (result.error) {
          Log.error(result.error);
        }
      } catch (err) {
        Log.error(err);
      }
    }
  }

  function lastImage() {
    index.value = index.value - 1 >= 0 ? index.value - 1 : props.images.length - 1;
  }

  function nextImage() {
    index.value = (index.value + 1) % props.images.length;
  }

  let toolBarTimer = 0;
  function toggleToolBar(visible?: boolean) {
    requestAnimationFrame(() => {
      if (typeof visible === "boolean") {
        toolBarVisible.value = visible;
      } else {
        toolBarVisible.value = !toolBarVisible.value;
      }
      emit("toolBarChange", toolBarVisible.value);
      if (toolBarVisible.value) {
        toolBarTimer && window.clearTimeout(toolBarTimer);
        toolBarTimer = window.setTimeout(() => {
          toolBarVisible.value = false;
          emit("toolBarChange", false);
        }, 3000);
      } else {
        toolBarTimer && window.clearTimeout(toolBarTimer);
      }
    });
  }

  function reset() {
    scale.value = 1;
    translate.value = { x: 0, y: 0 };
  }

  function isReset() {
    return scale.value === 1 && translate.value.x === 0 && translate.value.y === 0;
  }

  function calcAbsoluteContainedImageSize(img: HTMLImageElement) {
    const naturalW = img.naturalWidth;
    const naturalH = img.naturalHeight;
    if (!naturalW || !naturalH) return { width: 0, height: 0 };

    const boxW = img.offsetWidth;
    const boxH = img.offsetHeight;
    const imgRatio = naturalW / naturalH;
    const boxRatio = boxW / boxH;

    if (imgRatio > boxRatio) {
      // 图片更"宽"，宽度撑满，高度按比例
      return { width: boxW, height: boxW / imgRatio };
    } else {
      // 图片更"高"，高度撑满，宽度按比例
      return { width: boxH * imgRatio, height: boxH };
    }
  }

  function calcImageTranslateBounds() {
    const viewer = viewerRef.value;
    const image = imageRef.value;
    if (!viewer || !image) return { maxX: 0, maxY: 0 };

    const viewerWidth = viewer.clientWidth;
    const viewerHeight = viewer.clientHeight;

    const { width: baseW, height: baseH } = calcAbsoluteContainedImageSize(image);
    const scaledW = baseW * scale.value;
    const scaledH = baseH * scale.value;

    const maxX = Math.max(0, (scaledW - viewerWidth) / 2);
    const maxY = Math.max(0, (scaledH - viewerHeight) / 2);
    return { maxX, maxY };
  }

  function limitImageTranslate() {
    const { maxX, maxY } = calcImageTranslateBounds();
    translate.value.x = clamp(translate.value.x, -maxX, maxX);
    translate.value.y = clamp(translate.value.y, -maxY, maxY);
  }

  function center() {
    const image = imageRef.value;
    const viewer = viewerRef.value;
    if (!image || !viewer) return;

    const { width: containW, height: containH } = calcAbsoluteContainedImageSize(image);
    if (!containW || !containH) return;

    const viewerW = viewer.clientWidth;
    const viewerH = viewer.clientHeight;

    // 计算从 contain 到 cover 需要的缩放比例
    const scaleX = viewerW / containW;
    const scaleY = viewerH / containH;
    // 居中放大，translate 保持为 0
    scale.value = Math.max(scaleX, scaleY);
    translate.value = { x: 0, y: 0 };
  }

  function zoomAtPoint(clientX: number, clientY: number) {
    const viewer = viewerRef.value;
    if (!viewer) return;

    const viewerRect = viewer.getBoundingClientRect();
    // 鼠标相对于 viewer 中心的位置（因为图片是居中显示的）
    const centerX = viewerRect.width / 2;
    const centerY = viewerRect.height / 2;
    const mouseX = clientX - viewerRect.left - centerX;
    const mouseY = clientY - viewerRect.top - centerY;

    const prevScale = scale.value;
    const nextScale = isReset() ? 2 : 1;

    // 保持鼠标指向的图片上的点不变
    translate.value.x = mouseX - ((mouseX - translate.value.x) * nextScale) / prevScale;
    translate.value.y = mouseY - ((mouseY - translate.value.y) * nextScale) / prevScale;
    scale.value = nextScale;

    limitImageTranslate();
  }

  function onWheel(e: WheelEvent) {
    const viewer = viewerRef.value;
    if (!viewer) return;

    const rect = viewer.getBoundingClientRect();
    // 鼠标相对于 viewer 中心的位置（因为图片是居中显示的）
    const centerX = rect.width / 2;
    const centerY = rect.height / 2;
    const mouseX = e.clientX - rect.left - centerX;
    const mouseY = e.clientY - rect.top - centerY;

    const prevScale = scale.value;
    const delta = e.deltaY > 0 ? -0.1 : 0.1;
    const nextScale = clamp(scale.value + delta, 0.2, 5);

    // 保持鼠标指向的图片上的点不变
    translate.value.x = mouseX - ((mouseX - translate.value.x) * nextScale) / prevScale;
    translate.value.y = mouseY - ((mouseY - translate.value.y) * nextScale) / prevScale;

    scale.value = nextScale;
    limitImageTranslate();
  }

  function dClick(clientX: number, clientY: number) {
    if (isReset()) {
      zoomAtPoint(clientX, clientY);
    } else {
      reset();
    }
  }

  function click() {
    toggleToolBar();
  }

  let last = { x: 0, y: 0 };
  let startPos = { x: 0, y: 0 };
  function onPointerDown(e: PointerEvent) {
    dragging.value = true;
    moved.value = false;
    last = { x: e.clientX, y: e.clientY };
    startPos = { x: e.clientX, y: e.clientY };
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
  }

  function onPointerMove(e: PointerEvent) {
    if (!dragging.value) return;
    const dx = e.clientX - last.x;
    const dy = e.clientY - last.y;

    // 使用起始位置计算总移动距离，阈值设为 10 像素
    const totalDx = e.clientX - startPos.x;
    const totalDy = e.clientY - startPos.y;
    if (Math.abs(totalDx) + Math.abs(totalDy) > 10) {
      moved.value = true;
    }

    translate.value.x += dx;
    translate.value.y += dy;

    limitImageTranslate();

    last = { x: e.clientX, y: e.clientY };
  }

  let singleTapTimer = 0;
  let lastTapTime = 0;
  let lastTapPos = { x: 0, y: 0 };
  function onPointerUp(e: PointerEvent) {
    dragging.value = false;
    (e.currentTarget as HTMLElement).releasePointerCapture(e.pointerId);
    // 如果是移动过的，则不触发点击事件
    if (moved.value) return (moved.value = false);
    // 处理点击事件
    handleClickEvent(e);
  }

  function handleClickEvent(e: PointerEvent) {
    const now = performance.now();
    const tapDist = Math.hypot(e.clientX - lastTapPos.x, e.clientY - lastTapPos.y);
    // 双击条件：时间间隔小于 300ms、两次点击位置距离小于 30px
    if (now - lastTapTime < 300 && tapDist < 30) {
      singleTapTimer && window.clearTimeout(singleTapTimer);
      lastTapTime = 0;
      lastTapPos = { x: 0, y: 0 };
      dClick(e.clientX, e.clientY);
    } else {
      // 否则，记录本次点击时间和位置，等待单击定时器
      lastTapTime = now;
      lastTapPos = { x: e.clientX, y: e.clientY };
      singleTapTimer && window.clearTimeout(singleTapTimer);
      singleTapTimer = window.setTimeout(click, 300);
    }
  }
</script>

<style scoped lang="scss">
  .viewer {
    width: 100%;
    height: 100%;
    overflow: hidden;
    background: #000000;
    display: flex;
    justify-content: center;
    align-items: center;
    user-select: none;
    position: relative;
  }

  img {
    width: 100%;
    height: 100%;
    will-change: transform;
    object-fit: contain;
  }

  @mixin tool-bar {
    position: absolute;
    left: 0;
    right: 0;
    background: rgba(0, 0, 0, 0.7);
    backdrop-filter: blur(2px);
    z-index: 5;
    height: 36px;
    transition: all 0.5s ease-in-out;
  }

  .viewer-title {
    @include tool-bar;
    top: -36px;
    color: white;
    font-weight: 500;
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;
    user-select: none;

    &.active {
      top: 0;
    }
  }

  .viewer-button {
    @include tool-bar;
    bottom: -36px;
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 32px;

    &.active {
      bottom: 0;
    }
  }
</style>

// packages/ui/src/common/components/display/image/image-viewer.tsx
import { cx } from "@emotion/css";
import { clamp } from "lodash-es";
import {
  ArrowLeftToLine,
  ArrowRightToLine,
  Download,
  Image as ImageIcon,
  ImageOff,
  type LucideIcon,
  RotateCcw,
  ZoomIn,
  ZoomOut
} from "lucide-react";
import {
  type CSSProperties,
  type FC,
  memo,
  type PointerEvent as ReactPointerEvent,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type WheelEvent as ReactWheelEvent
} from "react";
import { useThemeInjectFromBus } from "@/common/hooks/use-theme-inject-from-bus";
import { RendererIPC } from "@/common/lib/ipc";
import { Log } from "@/common/lib/log";
import { RendererWindow } from "@/common/lib/window";
import AppToast from "@/common/components/display/toast";
import AppLoading from "@/common/components/fallback/app-loading";

export type ImageViewerEntry = {
  url?: string;
  alt?: string;
};

interface ImageViewerProps {
  images: ImageViewerEntry[];
  index: number;
  onIndexChange: NormalFunc<[index: number]>;
  onToolBarChange?: NormalFunc<[visible: boolean]>;
}

interface ToolbarButtonProps {
  icon: LucideIcon;
  label: string;
  disabled?: boolean;
  onClick?: NormalFunc;
}

const MIN_SCALE = 0.25;
const MAX_SCALE = 5;
const WHEEL_STEP = 0.12;
const BUTTON_ZOOM_STEP = 0.35;
const DOUBLE_TAP_DELAY = 300;
const DOUBLE_TAP_DISTANCE = 30;
const MOVE_THRESHOLD = 10;
const TOOLBAR_HIDE_DELAY = 3000;
const EMPTY_IMAGE: ImageViewerEntry = {};
const UNSAFE_FILE_NAME = /[<>:"/\\|?*]/g;

const ToolbarButton: FC<ToolbarButtonProps> = ({ icon: Icon, label, disabled, onClick }) => {
  return (
    <button
      type="button"
      aria-label={label}
      title={label}
      disabled={disabled}
      onClick={onClick}
      className={cx(
        `
          flex size-9 items-center justify-center rounded-md
          text-white/85 outline-none transition-all duration-200 ease-in-out
          hover:bg-white/15 hover:text-white active:scale-[0.92]
          focus-visible:ring-2 focus-visible:ring-white/45
        `,
        disabled && "pointer-events-none opacity-35"
      )}>
      <Icon className="size-4.5" />
    </button>
  );
};

const MemoToolbarButton = memo(ToolbarButton);

const ImageViewer: FC<ImageViewerProps> = ({ images, index, onIndexChange, onToolBarChange }) => {
  useThemeInjectFromBus();

  const viewerRef = useRef<HTMLDivElement>(null);
  const imageRef = useRef<HTMLImageElement>(null);
  const toolbarTimer = useRef<Nullable<number>>(null);
  const singleTapTimer = useRef<Nullable<number>>(null);
  const lastTapTime = useRef(0);
  const lastTapPos = useRef({ x: 0, y: 0 });
  const lastPointerPos = useRef({ x: 0, y: 0 });
  const startPointerPos = useRef({ x: 0, y: 0 });
  const moved = useRef(false);

  const [status, setStatus] = useState<"idle" | "loading" | "error" | "loaded">("idle");
  const [scale, setScale] = useState(1);
  const [translate, setTranslate] = useState({ x: 0, y: 0 });
  const [dragging, setDragging] = useState(false);
  const [toolBarVisible, setToolBarVisible] = useState(false);
  const [reloadToken, setReloadToken] = useState(0);

  const current = images[index] ?? images[0] ?? EMPTY_IMAGE;
  const hasImages = images.length > 0;
  const imageSrc = useMemo(() => {
    if (!current.url) return undefined;
    if (!reloadToken) return current.url;
    try {
      const url = new URL(current.url, window.location.href);
      url.searchParams.set("timestamp", String(reloadToken));
      return url.toString();
    } catch {
      return current.url;
    }
  }, [current.url, reloadToken]);

  const imageStyle = useMemo<CSSProperties>(
    () => ({
      transform: `translate(${translate.x}px, ${translate.y}px) scale(${scale})`,
      transition: dragging ? "none" : "transform 180ms ease",
      cursor: dragging ? "grabbing" : scale > 1 ? "grab" : "zoom-in"
    }),
    [dragging, scale, translate.x, translate.y]
  );

  const showToolbar = useCallback(
    (visible = true) => {
      setToolBarVisible(visible);
      onToolBarChange?.(visible);
      if (toolbarTimer.current) {
        window.clearTimeout(toolbarTimer.current);
        toolbarTimer.current = null;
      }
      if (visible) {
        toolbarTimer.current = window.setTimeout(() => {
          setToolBarVisible(false);
          onToolBarChange?.(false);
        }, TOOLBAR_HIDE_DELAY);
      }
    },
    [onToolBarChange]
  );

  const resetTransform = useCallback(() => {
    setScale(1);
    setTranslate({ x: 0, y: 0 });
  }, []);

  const calcContainedImageSize = useCallback((image: HTMLImageElement) => {
    const naturalW = image.naturalWidth;
    const naturalH = image.naturalHeight;
    if (!naturalW || !naturalH) return { width: 0, height: 0 };

    const boxW = image.offsetWidth;
    const boxH = image.offsetHeight;
    const imageRatio = naturalW / naturalH;
    const boxRatio = boxW / boxH;

    if (imageRatio > boxRatio) {
      return { width: boxW, height: boxW / imageRatio };
    }
    return { width: boxH * imageRatio, height: boxH };
  }, []);

  const calcImageTranslateBounds = useCallback(
    (nextScale = scale) => {
      const viewer = viewerRef.current;
      const image = imageRef.current;
      if (!viewer || !image) return { maxX: 0, maxY: 0 };

      const { width: baseW, height: baseH } = calcContainedImageSize(image);
      const scaledW = baseW * nextScale;
      const scaledH = baseH * nextScale;

      return {
        maxX: Math.max(0, (scaledW - viewer.clientWidth) / 2),
        maxY: Math.max(0, (scaledH - viewer.clientHeight) / 2)
      };
    },
    [calcContainedImageSize, scale]
  );

  const clampTranslate = useCallback(
    (value: { x: number; y: number }, nextScale = scale) => {
      const { maxX, maxY } = calcImageTranslateBounds(nextScale);
      return {
        x: clamp(value.x, -maxX, maxX),
        y: clamp(value.y, -maxY, maxY)
      };
    },
    [calcImageTranslateBounds, scale]
  );

  const zoomAtPoint = useCallback(
    (clientX: number, clientY: number, nextScale: number) => {
      const viewer = viewerRef.current;
      if (!viewer) return;

      const viewerRect = viewer.getBoundingClientRect();
      const mouseX = clientX - viewerRect.left - viewerRect.width / 2;
      const mouseY = clientY - viewerRect.top - viewerRect.height / 2;
      const safeNextScale = clamp(nextScale, MIN_SCALE, MAX_SCALE);

      setTranslate((prev) =>
        clampTranslate(
          {
            x: mouseX - ((mouseX - prev.x) * safeNextScale) / scale,
            y: mouseY - ((mouseY - prev.y) * safeNextScale) / scale
          },
          safeNextScale
        )
      );
      setScale(safeNextScale);
    },
    [clampTranslate, scale]
  );

  const zoomFromCenter = useCallback(
    (delta: number) => {
      const viewer = viewerRef.current;
      if (!viewer || status !== "loaded") return;
      const rect = viewer.getBoundingClientRect();
      zoomAtPoint(
        rect.left + rect.width / 2,
        rect.top + rect.height / 2,
        clamp(scale + delta, MIN_SCALE, MAX_SCALE)
      );
      showToolbar(true);
    },
    [scale, showToolbar, status, zoomAtPoint]
  );

  const lastImage = useCallback(() => {
    if (images.length <= 1) return;
    onIndexChange(index - 1 >= 0 ? index - 1 : images.length - 1);
    showToolbar(true);
  }, [images.length, index, onIndexChange, showToolbar]);

  const nextImage = useCallback(() => {
    if (images.length <= 1) return;
    onIndexChange((index + 1) % images.length);
    showToolbar(true);
  }, [images.length, index, onIndexChange, showToolbar]);

  const retryLoad = useCallback(() => {
    if (!current.url) return;
    resetTransform();
    setStatus("loading");
    setReloadToken(Date.now());
    showToolbar(true);
  }, [current.url, resetTransform, showToolbar]);

  const saveImage = useCallback(async () => {
    if (status !== "loaded" || !current.url) return;
    try {
      const response = await fetch(current.url);
      if (!response.ok) Log.throw({ message: "网络错误" });

      const contentType = response.headers.get("content-type");
      const buffer = await response.arrayBuffer();
      const name = createDownloadName(current, contentType);
      const result = await RendererIPC.Invoke("saveFile", { buffer, name });

      if (!result.ok) {
        result.error && Log.error(result.error);
        AppToast.show({ type: "error", text: "图片保存失败" });
        return;
      }
      AppToast.show({ type: "success", text: "图片已保存" });
    } catch (err) {
      Log.error(err);
      AppToast.show({ type: "error", text: "图片保存失败" });
    }
  }, [current, status]);

  const handleWheel = useCallback(
    (event: ReactWheelEvent<HTMLDivElement>) => {
      if (status !== "loaded") return;
      event.preventDefault();
      const delta = event.deltaY > 0 ? -WHEEL_STEP : WHEEL_STEP;
      zoomAtPoint(event.clientX, event.clientY, clamp(scale + delta, MIN_SCALE, MAX_SCALE));
      showToolbar(true);
    },
    [scale, showToolbar, status, zoomAtPoint]
  );

  const handlePointerDown = useCallback(
    (event: ReactPointerEvent<HTMLDivElement>) => {
      if (status !== "loaded" || event.button !== 0) return;
      setDragging(true);
      moved.current = false;
      lastPointerPos.current = { x: event.clientX, y: event.clientY };
      startPointerPos.current = { x: event.clientX, y: event.clientY };
      event.currentTarget.setPointerCapture(event.pointerId);
    },
    [status]
  );

  const handlePointerMove = useCallback(
    (event: ReactPointerEvent<HTMLDivElement>) => {
      if (!dragging) return;

      const dx = event.clientX - lastPointerPos.current.x;
      const dy = event.clientY - lastPointerPos.current.y;
      const totalDx = event.clientX - startPointerPos.current.x;
      const totalDy = event.clientY - startPointerPos.current.y;

      if (Math.abs(totalDx) + Math.abs(totalDy) > MOVE_THRESHOLD) {
        moved.current = true;
      }

      setTranslate((prev) => clampTranslate({ x: prev.x + dx, y: prev.y + dy }, scale));
      lastPointerPos.current = { x: event.clientX, y: event.clientY };
    },
    [clampTranslate, dragging, scale]
  );

  const toggleZoomAtPoint = useCallback(
    (clientX: number, clientY: number) => {
      const isReset =
        Math.abs(scale - 1) < 0.001 &&
        Math.abs(translate.x) < 0.001 &&
        Math.abs(translate.y) < 0.001;
      if (isReset) {
        zoomAtPoint(clientX, clientY, 2);
      } else {
        resetTransform();
      }
      showToolbar(true);
    },
    [resetTransform, scale, showToolbar, translate.x, translate.y, zoomAtPoint]
  );

  const handleTap = useCallback(
    (event: ReactPointerEvent<HTMLDivElement>) => {
      const now = performance.now();
      const tapDist = Math.hypot(
        event.clientX - lastTapPos.current.x,
        event.clientY - lastTapPos.current.y
      );

      if (now - lastTapTime.current < DOUBLE_TAP_DELAY && tapDist < DOUBLE_TAP_DISTANCE) {
        if (singleTapTimer.current) {
          window.clearTimeout(singleTapTimer.current);
          singleTapTimer.current = null;
        }
        lastTapTime.current = 0;
        lastTapPos.current = { x: 0, y: 0 };
        toggleZoomAtPoint(event.clientX, event.clientY);
        return;
      }

      lastTapTime.current = now;
      lastTapPos.current = { x: event.clientX, y: event.clientY };
      if (singleTapTimer.current) window.clearTimeout(singleTapTimer.current);
      singleTapTimer.current = window.setTimeout(() => {
        showToolbar(!toolBarVisible);
      }, DOUBLE_TAP_DELAY);
    },
    [showToolbar, toggleZoomAtPoint, toolBarVisible]
  );

  const handlePointerUp = useCallback(
    (event: ReactPointerEvent<HTMLDivElement>) => {
      if (!dragging) return;
      setDragging(false);
      if (event.currentTarget.hasPointerCapture(event.pointerId)) {
        event.currentTarget.releasePointerCapture(event.pointerId);
      }
      if (moved.current) {
        moved.current = false;
        return;
      }
      handleTap(event);
    },
    [dragging, handleTap]
  );

  useEffect(() => {
    if (!images.length) return;
    if (index > images.length - 1) onIndexChange(images.length - 1);
  }, [images.length, index, onIndexChange]);

  useEffect(() => {
    document.title = current.url ? current.alt || current.url : "Image Viewer";
    resetTransform();
    setReloadToken(0);
    setStatus(current.url ? "loading" : "idle");
  }, [current.alt, current.url, resetTransform]);

  useEffect(() => {
    const image = imageRef.current;
    if (image?.complete && image.naturalWidth > 0) {
      setStatus("loaded");
    }
  }, [imageSrc]);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.defaultPrevented) return;
      switch (event.key) {
        case "ArrowLeft":
          event.preventDefault();
          lastImage();
          break;
        case "ArrowRight":
          event.preventDefault();
          nextImage();
          break;
        case "Escape":
          event.preventDefault();
          RendererWindow.current.close();
          break;
        case "0":
          event.preventDefault();
          resetTransform();
          showToolbar(true);
          break;
        case "+":
        case "=":
          event.preventDefault();
          zoomFromCenter(BUTTON_ZOOM_STEP);
          break;
        case "-":
          event.preventDefault();
          zoomFromCenter(-BUTTON_ZOOM_STEP);
          break;
        case "s":
        case "S":
          if (event.ctrlKey || event.metaKey) {
            event.preventDefault();
            void saveImage();
          }
          break;
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [lastImage, nextImage, resetTransform, saveImage, showToolbar, zoomFromCenter]);

  useEffect(() => {
    return () => {
      toolbarTimer.current && window.clearTimeout(toolbarTimer.current);
      singleTapTimer.current && window.clearTimeout(singleTapTimer.current);
    };
  }, []);

  return (
    <div
      className="relative h-full w-full overflow-hidden bg-[#050505] text-white"
      onMouseMove={() => showToolbar(true)}>
      {/*背景*/}
      {current.url && (
        <img
          src={imageSrc}
          className={cx(
            `
              pointer-events-none absolute -inset-12 h-[calc(100%+96px)] w-[calc(100%+96px)]
              scale-105 object-cover opacity-0 blur-3xl transition-opacity duration-500
            `,
            status === "loaded" && toolBarVisible ? "opacity-50" : "opacity-35"
          )}
          alt={current.alt}
        />
      )}

      {/*标题栏*/}
      <div
        className={cx(
          `
            pointer-events-none absolute left-0 right-0 top-0 z-20 flex h-14
            items-center justify-center px-24 transition-all duration-300 ease-in-out
          `,
          toolBarVisible ? "translate-y-0 opacity-100" : "-translate-y-5 opacity-0"
        )}>
        <div
          className="
            flex min-w-0 max-w-[min(76vw,780px)] items-center gap-2 rounded-md
            border border-white/10 bg-black/35 px-4 py-1.5 text-[12px] font-semibold
            text-white/85 shadow-[0_8px_32px_rgba(0,0,0,0.25)] backdrop-blur-md
          ">
          <span className="truncate">{current.alt || current.url || "等待图片"}</span>
          {images.length > 1 && (
            <span className="shrink-0 text-white/55">{`${index + 1}/${images.length}`}</span>
          )}
        </div>
      </div>

      {/*内容（图片）区域*/}
      <div
        ref={viewerRef}
        className="relative z-10 flex h-full w-full items-center justify-center overflow-hidden"
        onWheel={handleWheel}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={handlePointerUp}
        onPointerLeave={handlePointerUp}>
        {imageSrc && (
          <img
            ref={imageRef}
            src={imageSrc}
            alt={current.alt}
            draggable={false}
            style={imageStyle}
            className={cx(
              `
                h-full w-full select-none object-contain opacity-0
                drop-shadow-[0_24px_60px_rgba(0,0,0,0.55)]
                transition-opacity duration-300 will-change-transform
              `,
              status === "loaded" && "opacity-100"
            )}
            onLoad={() => setStatus("loaded")}
            onError={() => setStatus("error")}
          />
        )}

        {status === "idle" && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 text-white/55">
            <ImageIcon className="size-12 opacity-75" />
            <p className="text-[13px] font-semibold">等待图片</p>
          </div>
        )}

        {status === "loading" && (
          <AppLoading
            loading
            tips="图片加载中"
            className="absolute inset-0 z-10 bg-black/20 text-white"
          />
        )}

        {status === "error" && (
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center gap-3 text-white/75">
            <ImageOff className="size-12 opacity-80" />
            <p className="text-[13px] font-semibold">图片加载失败</p>
            <button
              type="button"
              onClick={retryLoad}
              className="
                rounded-md border border-white/15 bg-white/10 px-3 py-1.5 text-[12px]
                font-semibold text-white/90 backdrop-blur-md transition-all duration-200
                ease-in-out hover:bg-white/15 active:scale-95
              ">
              重新加载
            </button>
          </div>
        )}
      </div>

      {/*工具栏*/}
      <div
        className={cx(
          `
            absolute bottom-4 left-1/2 z-30 flex -translate-x-1/2 items-center gap-1
            rounded-lg border border-white/10 bg-black/45 px-2 py-1.5
            shadow-[0_20px_60px_rgba(0,0,0,0.4)] backdrop-blur-xl
            transition-all duration-300 ease-in-out
          `,
          toolBarVisible
            ? "translate-y-0 opacity-100"
            : "pointer-events-none translate-y-6 opacity-0"
        )}>
        <MemoToolbarButton
          icon={ArrowLeftToLine}
          label="上一张"
          disabled={images.length <= 1}
          onClick={lastImage}
        />
        <MemoToolbarButton
          icon={ZoomOut}
          label="缩小"
          disabled={status !== "loaded" || scale <= MIN_SCALE}
          onClick={() => zoomFromCenter(-BUTTON_ZOOM_STEP)}
        />
        <button
          type="button"
          aria-label="重置缩放"
          title="重置缩放"
          disabled={status !== "loaded"}
          onClick={() => {
            resetTransform();
            showToolbar(true);
          }}
          className={cx(
            `
              flex h-9 min-w-18 items-center justify-center gap-2 rounded-md px-2
              text-[12px] font-semibold text-white/80 transition-all duration-200
              ease-in-out hover:bg-white/15 hover:text-white active:scale-95
              focus-visible:ring-2 focus-visible:ring-white/45
            `,
            status !== "loaded" && "pointer-events-none opacity-35"
          )}>
          <RotateCcw className="size-4" />
          <span>{Math.round(scale * 100)}%</span>
        </button>
        <MemoToolbarButton
          icon={ZoomIn}
          label="放大"
          disabled={status !== "loaded" || scale >= MAX_SCALE}
          onClick={() => zoomFromCenter(BUTTON_ZOOM_STEP)}
        />
        <MemoToolbarButton
          icon={Download}
          label="保存图片"
          disabled={status !== "loaded" || !hasImages}
          onClick={() => void saveImage()}
        />
        <MemoToolbarButton
          icon={ArrowRightToLine}
          label="下一张"
          disabled={images.length <= 1}
          onClick={nextImage}
        />
      </div>
    </div>
  );
};

function createDownloadName(image: ImageViewerEntry, contentType: Nullable<string>) {
  const fallbackName = getURLFileName(image.url) || "image";
  const baseName =
    stripControlChars(image.alt || fallbackName)
      .replace(UNSAFE_FILE_NAME, "_")
      .trim() || "image";
  const ext = getImageExtension(contentType) || getExtension(fallbackName) || "jpg";
  return ensureExtension(baseName.slice(0, 120), ext);
}

function getImageExtension(contentType: Nullable<string>) {
  const value = contentType?.split(";")[0]?.trim().toLowerCase();
  if (!value?.startsWith("image/")) return "";
  const ext = value.slice("image/".length);
  if (ext === "jpeg") return "jpg";
  if (ext === "svg+xml") return "svg";
  return ext || "";
}

function getURLFileName(url: Optional<string>) {
  if (!url) return "";
  try {
    const path = new URL(url, window.location.href).pathname;
    return decodeURIComponent(path.split("/").filter(Boolean).at(-1) || "");
  } catch {
    return url.split("/").filter(Boolean).at(-1) || "";
  }
}

function getExtension(fileName: string) {
  const ext = fileName.split(".").at(-1);
  if (!ext || ext === fileName) return "";
  return ext.replace(UNSAFE_FILE_NAME, "").toLowerCase();
}

function stripControlChars(value: string) {
  return [...value].filter((char) => char.charCodeAt(0) >= 32).join("");
}

function ensureExtension(fileName: string, ext: string) {
  const normalizedExt = ext.replace(/^\./, "");
  if (!normalizedExt) return fileName;
  if (fileName.toLowerCase().endsWith(`.${normalizedExt.toLowerCase()}`)) return fileName;
  return `${fileName}.${normalizedExt}`;
}

export default memo(ImageViewer);
