// packages/ui/src/common/components/fallback/app-loading.tsx
import Loading from "./loading";
import { type FC, memo, type ReactNode, type RefObject } from "react";
import { cx } from "@emotion/css";

interface ListLoadingProps {
  ref?: RefObject<Nullable<HTMLDivElement>>;
  loading: boolean;
  children?: ReactNode;
  className?: string;
  tips?: string;
  wrap?: boolean;
}

const AppLoading: FC<ListLoadingProps> = ({
  loading,
  children,
  className,
  tips = "数据努力加载中",
  ref,
  wrap
}) => {
  if (!loading) {
    if (wrap) return <div ref={ref}>{children}</div>;
    return children;
  }
  return (
    <div
      ref={ref}
      className={cx(
        "px-2 py-1 w-full h-full flex flex-col gap-2 justify-center items-center text-center",
        className
      )}>
      <Loading className="size-8" />
      <span className="font-semibold">{tips}</span>
    </div>
  );
};

export default memo(AppLoading);

// ui/src/public/components/fallback/AppLoading.vue
<template>
  <div
    v-if="props.loading"
    :style="{ color: props.color }"
    class="px-2 py-1 w-full h-full flex flex-col gap-2 justify-center items-center text-white">
    <Loading class="size-8" />
    <span class="font-semibold">{{ props.tips }}</span>
  </div>
  <slot v-else name="default" />
</template>

<script setup lang="ts" name="AppLoading">
  import { ReactNode } from "react";
  import Loading from "@mahiru/ui/public/components/public/Loading.vue";

  const props = withDefaults(
    defineProps<{
      loading: boolean;
      color?: string;
      children?: ReactNode;
      tips?: string;
    }>(),
    {
      tips: "数据努力加载中"
    }
  );
</script>

<style scoped lang="scss"></style>
