// ui/src/public/components/public/TopControlPure.vue
<template>
  <NoDrag class="flex flex-row gap-4 select-none relative z-10">
    <Chromium
      v-if="isDev"
      :color="props.color"
      class="size-5 control-button"
      @click="Renderer.event.openDevTools" />
    <Minus
      v-if="props.mini"
      :color="props.color"
      class="size-5 control-button"
      @click="Renderer.event.minimize" />
    <Square
      v-if="props.maximizable"
      v-show="isMax"
      :color="props.color"
      class="size-5 control-button"
      @click="maximize" />
    <SquareMinus
      v-if="props.maximizable"
      v-show="!isMax"
      :color="props.color"
      class="size-5 control-button"
      @click="maximize" />
    <X :color="props.color" class="size-5 control-button" @click="close" />
  </NoDrag>
</template>

<script setup lang="ts" name="TopControlPure">
  import NoDrag from "@mahiru/ui/public/components/drag/NoDrag.vue";
  import { Chromium, Minus, Square, SquareMinus, X } from "lucide-vue-next";
  import { isDev } from "@mahiru/ui/public/utils/dev";
  import { Renderer } from "@mahiru/ui/public/entry/renderer";
  import { runCloseTask } from "@mahiru/ui/public/utils/close";
  import { onMounted, ref } from "vue";

  const isMax = ref(false);

  const props = withDefaults(
    defineProps<{
      maximizable?: boolean;
      mini?: boolean;
      color?: string;
    }>(),
    {
      mini: true
    }
  );

  function close() {
    Renderer.event.hidden();
    runCloseTask();
  }

  function maximize() {
    if (isMax.value) {
      Renderer.event.unmaximize();
      isMax.value = false;
    } else {
      Renderer.event.maximize();
      isMax.value = true;
    }
  }

  onMounted(() => {
    Renderer.invoke.isMaximized().then((max) => {
      isMax.value = max;
    });
  });
</script>

<style scoped lang="scss">
  .control-button {
    cursor: pointer;
    scale: 80%;
    transition: all ease-in-out 0.3s;

    &:hover {
      opacity: 0.5;
    }
  }
</style>

// ui/src/public/components/public/TopControlPure.tsx
import { FC, memo, useCallback, useEffect, useState } from "react";
import { Chromium, Minus, Square, SquareMinus, X } from "lucide-react";
import { runCloseTask } from "@mahiru/ui/public/utils/close";
import { Renderer } from "@mahiru/ui/public/entry/renderer";
import { isDev } from "@mahiru/ui/public/utils/dev";

import NoDrag from "@mahiru/ui/public/components/drag/NoDrag";

interface TopControlPurProps {
  maximizable?: boolean;
  mini?: boolean;
  color?: string;
}

const TopControlPure: FC<TopControlPurProps> = ({ maximizable, mini = true, color }) => {
  const [isMax, setIsMax] = useState(false);

  useEffect(() => {
    Renderer.invoke.isMaximized().then(setIsMax);
  }, []);

  const maximize = useCallback(() => {
    if (isMax) {
      setIsMax(false);
      Renderer.event.unmaximize();
    } else {
      setIsMax(true);
      Renderer.event.maximize();
    }
  }, [isMax]);

  const close = useCallback(() => {
    Renderer.event.hidden();
    runCloseTask();
  }, []);

  return (
    <NoDrag className="flex flex-row gap-4 select-none relative z-10">
      {isDev && (
        <Chromium
          color={color}
          className="size-5 cursor-pointer hover:opacity-50 ease-in-out transition-all duration-300"
          onClick={Renderer.event.openDevTools}
        />
      )}
      {mini && (
        <Minus
          color={color}
          className="size-5 cursor-pointer hover:opacity-50 ease-in-out transition-all duration-300"
          onClick={Renderer.event.minimize}
        />
      )}
      {maximizable &&
        (isMax ? (
          <SquareMinus
            color={color}
            className="size-5 cursor-pointer scale-80 hover:opacity-50 ease-in-out transition-all duration-300"
            onClick={maximize}
          />
        ) : (
          <Square
            color={color}
            className="size-5 cursor-pointer scale-80 hover:opacity-50 ease-in-out transition-all duration-300"
            onClick={maximize}
          />
        ))}
      <X
        color={color}
        className="size-5 cursor-pointer hover:opacity-50 ease-in-out transition-all duration-300"
        onClick={close}
      />
    </NoDrag>
  );
};

export default memo(TopControlPure);
